- name: Deploy 3-tier Book Review App
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
    ansible_python_interpreter: /home/codespace/.python/current/bin/python

  tasks:

    - name: Create dev namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace }}"

    - name: Deploy MySQL
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: mysql
            namespace: "{{ namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: mysql
            template:
              metadata:
                labels:
                  app: mysql
              spec:
                containers:
                  - name: mysql
                    image: "{{ mysql_image }}"
                    env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: "{{ mysql_root_password }}"
                      - name: MYSQL_DATABASE
                        value: "{{ mysql_database }}"
                    ports:
                      - containerPort: 3306

    - name: Expose MySQL Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: mysql
            namespace: "{{ namespace }}"
          spec:
            selector:
              app: mysql
            ports:
              - port: 3306
                targetPort: 3306
            type: ClusterIP

    - name: Wait for MySQL pod to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ namespace }}"
        label_selectors:
          - app=mysql
      register: mysql_pods
      until: mysql_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 0
      retries: 10
      delay: 5

    - name: Deploy Backend
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: backend
            namespace: "{{ namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: backend
            template:
              metadata:
                labels:
                  app: backend
              spec:
                containers:
                  - name: backend
                    image: "{{ backend_image }}"
                    imagePullPolicy: Always
                    env:
                      - name: DB_HOST
                        value: "mysql"
                      - name: DB_NAME
                        value: "{{ mysql_database }}"
                      - name: DB_USER
                        value: "root"
                      - name: DB_PASS
                        value: "{{ mysql_root_password }}"
                      - name: DB_DIALECT
                        value: "mysql"
                      - name: PORT
                        value: "{{ backend_port |int }}"
                      - name: JWT_SECRET
                        value: "mysecretkey"
                      - name: ALLOWED_ORIGINS
                        value: "http://frontend"
                    ports:
                      - containerPort: "{{ backend_port |int }}"

    - name: Expose Backend Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: backend
            namespace: "{{ namespace }}"
          spec:
            selector:
              app: backend
            ports:
              - port: "{{ backend_port |int }}"
                targetPort: "{{ backend_port |int }}"
            type: ClusterIP

    - name: Deploy Frontend
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: frontend
            namespace: "{{ namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: frontend
            template:
              metadata:
                labels:
                  app: frontend
              spec:
                containers:
                  - name: frontend
                    image: "{{ frontend_image }}"
                    imagePullPolicy: Always
                    env:
                      - name: NEXT_PUBLIC_API_URL
                        value: "http://backend:{{ backend_port |int }}"
                    ports:
                      - containerPort: "{{ frontend_port |int }}"

    - name: Expose Frontend Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: frontend
            namespace: "{{ namespace }}"
          spec:
            selector:
              app: frontend
            ports:
              - port: 80
                targetPort: "{{ frontend_port |int }}"
                nodePort: "{{ frontend_node_port|int }}"
            type: NodePort
